Графика для всех страниц
htmlacademy-htmlcss/2282025-sedona-36 pull request #3
Opened 2023-01-28 16:43 UTC by GluhovaAn

2023-01-28 16:47 UTC, GluhovaAn commented
История коммитов получилась запутанная...По итогу 2 последних коммита это полностью готовое домашнее задание^^

2023-01-29 14:03 UTC, redsmoke19 requested changes
Ну и общий комментарий по работе, во первых убрать / исправить те замечания которые я написал в коде, а так же не нужно создавать кучу папок в которые ты размещаешь изображения типо такой `images/catalog/product/hotel-3.jpg`
Тебе достаточно внутри папки images завести две папки index и catalog и складывать в них все изображения отосящиеся к каждой из страницы

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +        alt="Логотип сайта Седона">
В конце альта должна быть точка)

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +      <img class="hero-step" src="images/index/hero/step.svg" width="1200" height="57" alt="Декоротивный элемент">
Декоративный элемент нужно убрать из разметки, мы его потом вставим с помощью css

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +          <img class="addition-img" src="images/index/addition/house.svg" width="74" height="72" alt="">
Эти иконки так же нужно убрать из разметки, мы их потом вставим через цсс

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +      <img class="subscribe-img" src="images/index/subscribe/subscribe-background.jpg" width="1200" height="415" alt="">
это не является контентным изображением, из разметки нужно убрать

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +            <img class="footer-social-img" src="images/index/footer/vk.svg" width="24" height="14" alt="">
Так же иконки - не контентные изображения, из разметки нужно убрать

2023-01-29 14:03 UTC, redsmoke19 commented on index.html
> +        <img class="footer-developer-logo" src="images/index/footer/logo-html-academy.svg" width="115" height="33"
и это не контентное - нужно убрать

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +            <img class="navnavigation-user-img" src="images/catalog/header/search-header.svg" width="20" height="20"
иконки в шапку нужно убрать из разметки, мы их позже вставим (на главной и каталоге убрать)

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +        <img class="breadcrumbs-img" src="images/catalog/breadcrumbs/arrow.svg" width="8" height="20" alt="">
это не контентное изображение, нужно убрать из разметки

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +            <img class="breadcrumbs-img" src="images/catalog/breadcrumbs/home.svg" width="13" height="14" alt="">
это не контентное изображение, нужно убрать из разметки

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +        <img class="catalog-hotel-filters-img" src="images/catalog/filtr/filtr-backgraund.jpg" width="1200" height="412"
это не контентное изображение, нужно убрать из разметки, потому добавим через цсс

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +        <img class="select-control-img" src="images/catalog/sorting/arrow-down.svg" width="12" height="7" alt="">
это не контентное изображение, нужно убрать из разметки

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +            <img class="sort-img" src="images/catalog/sorting/card.svg" width="16" height="14" alt="">
это не контентное изображение, нужно убрать из разметки

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +            <img class="sort-img" src="images/catalog/sorting/one-card.svg" width="16" height="14" alt="">
это не контентное изображение, нужно убрать из разметки

2023-01-29 14:03 UTC, redsmoke19 commented on catalog.html
> +            <img class="sort-img" src="images/catalog/sorting/list.svg" width="16" height="14" alt="">
это не контентное изображение, нужно убрать из разметки

2023-02-01 05:07 UTC, merged